### ISSUE TITLE
Archipelago Generation not working

### ISSUE THREAD

**Issue by Battlestar14** [NikolajDanger/APSly2#5]
The Generation w

[Sly.2.yaml](https://github.com/user-attachments/files/24173810/Sly.2.yaml)

ith the Archipelago Launcher is not working i always get the following error

Archipelago (0.6.4) logging initialized on Windows-11-10.0.26200-SP0 process 6040 running Python 3.12.10 (frozen)
P1 Weights: Simplified.Ratchet.Clank.2.yaml >> No description specified
P2 Weights: Sly.2.yaml >> Default Sly 2: Band of Thieves Template
P3 Weights: Sora.yaml >> Generated by https://archipelago.gg/ for Kingdom Hearts 2
Generating for 3 players, 69920223647045440926 Seed 91452078350693995852 with plando: connections, texts, bosses
Invalid or missing manifest file for C:\ProgramData\Archipelago\custom_worlds\rac2.apworld. This apworld will stop working with Archipelago 0.7.0.
There is no item named 'archipelago.json' in the archive - This might be the incorrect world version for this file
Could not load world WorldSource(C:\ProgramData\Archipelago\custom_worlds\sly2 (1).apworld, is_zip=True, relative=False):
Traceback (most recent call last):
  File "worlds\__init__.py", line 60, in load
  File "<frozen importlib._bootstrap>", line 810, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
Traceback (most recent call last):
  File "worlds\__init__.py", line 60, in load
  File "<frozen importlib._bootstrap>", line 810, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
Traceback (most recent call last):
  File "Generate.py", line 207, in main
  File "Generate.py", line 207, in <genexpr>
  File "Generate.py", line 522, in roll_settings
Exception: No world found to handle game Sly 2: Band of Thieves. Did you mean 'Ocarina of Time' (36% sure)? Check your spelling or installation of that world.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 133, in run
  File "console.py", line 25, in run
  File "Generate.py", line 592, in <module>
  File "Generate.py", line 230, in main
ValueError: File Sly.2.yaml is invalid. Please fix your yaml.

Am i doing something wrong or is it a general problem
